# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables.yml


steps:
- script: ls -l
  displayName: 'List Directory'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 
    arguments: '-t my-source-cli:latest'
  displayName: 'Build dockerfile'

- script: sudo docker run -e "AS_LICENSE_TYPE=$(AS_LICENSE_TYPE)"" -e "AS_LICENSE_SERVER=hclsoftware-uat" -e "AS_LICENSE_SERVER_ID=3MYLKMNGTJ5X" -e "AS_INSTALL_MODE=standalone" -v "$(pwd):/host" my-source-cli "script /host/azure-source-cli.script"
  displayName: 'AppScan Source'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'report_FP.pdf'
    targetPath: '$(Pipeline.Workspace)'