name: "HCL AppScan On Cloud SAST"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan Static Analyzer
        uses: HCL-TECH-SOFTWARE/appscan-static-analyzer-action@v1
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: e35ea96d-cae0-499a-a3ed-7a4efd77b269
          wait_for_analysis: true
          scan_build_outputs: true
